---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: main
      containers:
      - image: nginx:1-alpine-perl
        name: main
